// 서버 컴포넌트
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ClientProviders from "./ClientProviders"; // ✅ 클라이언트 전용 감싸기

export const metadata = {
  title: "Rumiware",
  description: "Generated by create next app",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClientProviders>
          {children}
        </ClientProviders>
      </body>
    </html>
  );
}
